### ISSUE TITLE
HTTP URL mapping for objects

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#112]
This came up from IETF99 - the idea of having a URL template as part of authentication which defined a URI for each "object" at which a client could GET / PUT / PATCH / DELETE the object in isolation with a REST-style call rather than using JMAP getFoos/setFoos to interact with it.

Even if this existed, what about getFooList and getFooUpdates/getFooListUpdates - how would they look?

**Comment by cjnewman** [comment]
I'll note that RFC 6578 is the CalDAV/WebDAV mechanism equivalent to getFooUpdates/getFooListUpdates. Personally, I much prefer the getFooUpdates/getFooListUpdates model.

**Comment by neilj** [comment]
Having talked to Mark Nottingham, he's happy that we're not just reinventing HTTP and tunnelling it over HTTP, and the concepts we're introducing are useful and don't really have a direct map to HTTP (which is why we're doing what we're doing). While you could introduce a basic HTTP GET / POST / PATCH / DELETE model, it would be missing an awful lot of functionality that's just not easily expressible in this model. I think it's out of scope for the group to define such a mapping; we want one consistent access model defined in the spec to keep it as simple as possible.
