### ISSUE TITLE
define collation (RFC 4790) for all sorts

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#125]
sortOrder: don't hand-wave the locale-specific character order problem
as that breaks interoperability. I suggest abstracting the problem by
associating a collation (RFC 4790) with each account. If there's a
collation associated with the account, that produces a deterministic
order. Otherwise, permission has been given to be
non-deterministic. Server operators can derive the collation algorithm
name from the user's language when they register their account; then
it will work even on a client with the wrong locale configured.

**Comment by brong** [comment]
Chris Newman again:

3.1.2. Sorting


We have a collation model (RFC 4790) that covers sorting. I think
servers need to implement either RFC 5051 or the Unicode Collation
Algorithm as a minimum/default. Allowing a collation to be specified
would be good for interoperabiltiy/predictability.

**Comment by neilj** [comment]
A sort string is currently two parts (property + asc/desc), separated by a space. I'm thinking we add an optional third part which is a collation algorithm identifier (e.g. `i;ascii-casemap`) from the registry, as defined in RFC4790, defaulting to `i;unicode-casemap` if omitted.

e.g. sort argument to getMailboxList: `[ "sortOrder asc", "name asc i;unicode-casemap" ]`

If the server doesn't support the requested collation you could get an error.

@cjnewman Does that sound reasonable to you?

**Comment by brong** [comment]
I'm getting less and less happy about the structure of this bloody
thing.  Once you have 3 positional parameters, you've probably
missed some.[1]
I'd rather make the sort argument be objects with named parameters if we
think we might need to extend it:
getMailboxList: [ { "field" : "sortOrder" }, { "field" : "name", "collation", "i;unicode-casemap" } ],
With default of ascending for sort order once you start doing named
parameters (same as SQL), as well as the default collation for
string types.
Bron.

[1] https://en.wikiquote.org/wiki/Alan_Perlis

On Mon, 20 Nov 2017, at 16:39, Neil Jenkins wrote:
> A sort string is currently two parts (property + asc/desc), separated
> by a space. I'm thinking we add an optional third part which is a
> collation algorithm identifier (e.g. i;ascii-casemap) from the
> registry, as defined in RFC4790, defaulting to i;unicode-casemap if
> omitted.> e.g. sort argument to getMailboxList: [ "sortOrder asc", "name asc i;unicode-
>      casemap" ]> If the server doesn't support the requested collation you could get
> an error.> @cjnewman[1] Does that sound reasonable to you?


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].> 

--
  Bron Gondwana, CEO, FastMail Pty Ltd
  brong@fastmailteam.com



Links:

  1. https://github.com/cjnewman
  2. https://github.com/jmapio/jmap/issues/125#issuecomment-345596656

**Comment by neilj** [comment]
Yeh, I agree.

**Comment by cjnewman** [comment]
I'd recommend being vague about the default collation algorithm. It needs the following properties:

1. MUST be Unicode-aware
2. SHOULD have reasonable default behavior for many languages when the user's language is unknown.
3. MAY be selected based on out-of-band information about the user's language/locale.

Two examples that meet these requirements are the "i;unicode-casemap" collation and the Unicode Collation Algorithm (http://www.unicode.org/reports/tr10/).

In practice, implementations will use whatever collation algorithm is offered by the i18n library they use as the default (so UCA is more likely in practice than i;unicode-casemap).

Earlier drafts of the collation registry tried to register UCA as a collation:
  https://tools.ietf.org/html/draft-newman-i18n-comparator-12 
but that was removed due to an unrealistic IETF dogma (must specify unicode version) at the time that made it controversial. I think that IETF dogma has been eliminated by reality (the unicode version is determined by the i18n library version linked against the software and not by anything specifications say). So now it should be possible to IANA register UCA-based collations for language variants as soon as that feature is needed.
