### ISSUE TITLE
What exactly should creating new user create?

### ISSUE THREAD

**Issue by matoous** [jmapio/jmap#147]
Hello,
After reading the specification I would like to know, what all shall be done when creating new user?
The user needs to have an User object (with password etc.), Account object (since one user can have access to more accounts) and Identity object. Is that all?
Also, what is the relation between Identity and Account, can more accounts have same identity, or does it tie with user as written in documentation?

> A Identity object stores information about an email address (or domain) the user may send from.

Thanks :)

**Comment by neilj** [comment]
For a mail (only) user, I would expect you would probably create the following when creating a new user:

* An Account for the user (if the user can access multiple accounts, this is usually because other users have shared their account with the user; each user normally has a single "primary" account which belongs to them).
* Default Mailboxes for the account (e.g. Inbox, Archive, Drafts, Sent, Spam, Trash; depends on your platform which ones you need).
* An Identity for the user's primary email address.

> Also, what is the relation between Identity and Account, can more accounts have same identity, or does it tie with user as written in documentation?

An Identity stores information about an email address or domain you can send from with that account. Multiple accounts may have identities with the same email address/domain; what identities are allowed for an account is a policy decision for the server.
