### ISSUE TITLE
Add Mailbox#isSubscribed property

### ISSUE THREAD

**Issue by neilj** [jmapio/jmap#204]
Exposes the \Subscribed IMAP flag.

**Comment by cjnewman** [comment]
I'm not convinced the IMAP subscription model should be carried into JMAP, as I think it was designed incorrectly. In order to render shared folders reasonably, clients need to understand the distinction between "personal folders" and "subscribed shared folders".

In general, the mail client operations of interest are:
1. show my personal folders.
2. show my personal & subscribed-shared folders
3. browse/search all shared folders to look for interesting ones that might be worth a subscription.

I don't think it's useful to subscribe to a personal folder, nor do I think it's useful to view a mixture of non-subscribed shared folders with personal folders.

Another issue is where seen flag information is stored. Should a server offering shared folders be required to hold seen/flag information for all uses who can login, or should the seen/flag information be kept with the user's account (which might be on another server)? The IMAP model favors the reverse-newsrc storage model over the newsrc storage model. I tend to think the newsrc storage model makes more sense from a perspective of quota management and functional isolation (so a shared folder server can be read-only with respect to flags).

Given what I know now, I'd be inclined to make sure JMAP can perform function 2 easily, something IMAP does not do well.

**Comment by neilj** [comment]
> In order to render shared folders reasonably, clients need to understand the distinction between "personal folders" and "subscribed shared folders".

With JMAP the shared mailboxes are a different "account" to your personal one (which will be marked the primary one by the server). This already allows you to easily implement a client that does what you're wanting (1, 2 & 3).

I've created https://github.com/jmapio/jmap/pull/205 with the suggested change; @cjnewman  can you please review?

A client can query on the isSubscribed property in Mailbox/query to just fetch the subscribed mailboxes in a shared account by default (for example), but then offer a UI where it fetched the full list for the user to configure their subscriptions. Meanwhile, it might ignore the property in the default account and always show everything; this is really all up to what the client is designed for, but adding the property does allow for this capability to be added and synchronised between clients (it's redundant if it's only used on one client of course).

**Comment by cjnewman** [comment]
That model makes sense. Is this model for shared folders discussed somewhere in the document?

**Comment by neilj** [comment]
I've added a further explanation of this in 94edbc1.
