### ISSUE TITLE
Email/Query: attachments filter

### ISSUE THREAD

**Issue by shyoracle** [jmapio/jmap#215]
What shall the "attachments" query return? 
- "a message have an attachment containing this text?".  or 
- "an attachment in a message containing this text?"

**Comment by neilj** [comment]
Email/query is a query on the email type and always returns a list of email ids. The attachments filter condition means the email matches if it has an attachment that contains the given text.

**Comment by shyoracle** [comment]
If that's case, isn't text search for this purpose? Does a user care if it is an email main body or attachment? Come back the old question, when they want to search attachment, they probably want to know which attachment has the term. Therefore, an attachment ID or part ID is probably expected. 

If they don't really care, why can't we simplify it to text search or body search, which is consistent with IMAP syntax.

**Comment by neilj** [comment]
This is just like body vs. text. Using "text" searches all textual fields. But if you want to refine the search to a specific location you can use "subject" or "body" or "attachments" to just search this particular part of the message.

Regarding returning which particular attachment matches, this is something we are considering adding to the SearchSnippet object.

**Comment by cjnewman** [comment]
In IMAP, "text" is search the entire message, and "body" is search the entire message except for the headers. There's no search key in IMAP to search just attachments. So there's no way to map the JMAP "attachments" functionality to IMAP. I propose moving "attachments" out of the base JMAP mail spec because it doesn't map to IMAP and doesn't seem to have a compelling use case. I don't object to a JMAP extension with "attachments".
