### ISSUE TITLE
Email/import should become Foo/import with create rather than "emails"

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#262]
Another case of implementing new data types.  Foo/import should take the same arguments as Foo/parse and Foo/copy.

Further more, Foo/parse and Foo/import should take a "type" parameter which is the content-type of the data in the blob.

 aka: an import of an email might look like:

['Email/import', {
  create: {
    k1 => {
      mailboxIds: ['A'],
      blobId: "Gabcdef",
      keywords: { "foo": true },
      type: "message/rfc822"
    }
  }  
}, '1']

The import of a CalendarEvent might look like:

['CalendarEvent/import', {
  create: {
    k1 => {
      calendarId: 'C1',
      blobId: "Gabcdef",
      type: "text/calendar"
    }
  }  
}, '1']

And like with Foo/copy, you should be able to set any other properties (or indeed patch paths) to overwrite those in the blob during the import.

**Comment by brong** [comment]
Each object (Foo) could specify a default type, so the default for Email/import would be message/rfc822, or even have an "autodetect" default.  This would be particularly interesting for calendar which have an XML and a JSON representation too.

**Comment by neilj** [comment]
I don't think this can be generic like this. Email is special because the underlying datastore is not the same format as the JSON object representation. With calendars, for example, you might use JSCalendar as the store so it's the same. More importantly though, suppose you import an iCalendar file – this may have many events in it, not just one. So you need to be able to represent which ones to import, and what happened. This is different enough that I think trying to define this as a generic method is more painful than having domain-specific ones.
