### ISSUE TITLE
draft-ietf-jmap-mail: sibling mailboxes with the same name

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#64]
In Section 2:

  o  *name*: "String" User-visible name for the mailbox, e.g.  "Inbox".
      This may be any UTF-8 string of at least 1 character in length and
      maximum 256 bytes in size.  Servers SHOULD forbid sibling
      Mailboxes with the same name.

The last SHOULD - why? There is no such requirement in IMAP.

**Comment by brong** [comment]
@aamelnikov by definition you can't have sibling mailboxes with the same name in IMAP.

INBOX
Folder
Folder/sub
Folder/sub

That would be siblings with the same name.  How would you select them?

Since JMAP has unique IDs, you could theoretically have two folders with the same name, but IMAP compatibility would be a mess.
