### ISSUE TITLE
draft-ietf-jmap-core: authentication framework

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#84]
2.2.1.  200: Success, but more authorization required.

   The response body will be a single JSON object with the following
   properties.

   o  *loginId*: "String" An id from the server to allow it to connect
      the next request with previous requests in the login process.
      This SHOULD be of limited time validity (e.g. 15 minutes from
      previous call).

   o  *methods*: "AuthMethod[]" A list of the supported authentication
      methods to continue with authentication.  See below for definition
      of the *AuthMethod* object.

   o  *prompt*: "String|null" A message to display in the client to the
      user.  The client MUST treat this as plain text, but SHOULD
      automatically hyperlink any URLs it finds if a system browser is
      available.

   This is the standard response to an initial request.  Note, a server
   may return this even if the username is not actually active, to
   prevent enumeration.  The client should then pick one of the
   _methods_ from the list in the response to continue with
   authentication (if no methods supported by the client are in the
   list, it will not be able to get an access token).

   An *AuthMethod* object MUST have a *type* property.  This is a
   "String" representing the method of authentication.  For some types,
   there may be other values required on the AuthMethod object in
   addition; see the description of types below.  The following types
   are currently defined, but more may be added in the future.  A client
   SHOULD offer the user the option to choose any of the method types
   returned that the client supports.  The client MUST ignore any types
   it does not understand:

It would be good to either reuse SASL authentication framework here or at least hook into existing authentication mechanisms (e.g. Digest, as well as <https://datatracker.ietf.org/wg/httpauth/documents/>).

**Comment by robn** [comment]
It might be good to show how to use SASL mechanisms over the top, but SASL isn't suitable on its own because it has no support for multiple mechanisms within a single auth handshake.

(a "multi-mechanism" SASL mechanism that wraps a sequence of others is something I've wanted but I suspect trying to construct one is going to take us down a rabbit hole we don't want to go right now).

I wonder if it would be worth splitting the auth methods out into separate documents? New auth mechanisms will be likely be added over time, and old ones fall out of use. Having a set baked into the core spec might not be wise.

**Comment by neilj** [comment]
As per the discussion at IET99, we're going to split the auth stuff out of the spec (#105). I don't think there's anything more to do on this particular issue therefore.
